---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
    flatten_output: true
    output_path: filetree

  pre_tasks:
    - name: Use the 'find' module to locate files
      ansible.builtin.find:
        paths: 
          - "."
        recurse: false       
        file_type: any      
      register: found_files

    - name: Display the list of found file paths
      ansible.builtin.debug:
        msg: "{{ item.path }}"
      loop: "{{ found_files.files }}"

    - name: "Setup authentication (block)"
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ aap_hostname }}/api/gateway/v1/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always

    - name: Eliminar el directorio .git del clon para un nuevo historial
      ansible.builtin.file:
        path: "{{ output_path }}"
        state: absent
  roles:
    - infra.aap_configuration_extended.filetree_create

  post_tasks:

    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ aap_hostname }}{{ aap_oauthtoken_url }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined

    - name: Commit push filetree
      ansible.builtin.command: "git status filetree -s"
      register: status_git

    - debug:
        msg: "{{status_git}}"

    - name: Commit push filetree
      ansible.builtin.command: "{{ item }}"
      loop:
        - git init
        - git add filetree/.
        - git commit -m 'Add new version filetree'
        - git push
      when: status_git.msg  | length > 0
